# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - provider-kubernetes-config.yaml
  - provider-config.yaml
  - providers.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/runtimeConfigRef
        value:
          name: workload-identity
    target:
      group: pkg.crossplane.io
      version: v1
      kind: Provider
      name: upbound-provider-family-gcp
  - patch: |-
      - op: add
        path: /spec/runtimeConfigRef
        value:
          name: workload-identity
    target:
      group: pkg.crossplane.io
      version: v1
      kind: Provider
      name: upbound-provider-gcp-cloudplatform
