apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: keycloak-config
  namespace: keycloak
spec:
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: keycloak
  target:
    name: keycloak-config
    template:
      data:
        POSTGRES_PASSWORD: "{{ .postgresPassword }}"
        KEYCLOAK_ADMIN_PASSWORD: "{{ .keycloakAdminPassword }}"
        KEYCLOAK_USER_PASSWORD: "{{ .keycloakUserPassword }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: "postgres-keycloak-password"
      rewrite:
        - transform:
            template: "postgresPassword"
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: "postgres-keycloak-password"
      rewrite:
        - transform:
            template: "keycloakAdminPassword"
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: "keycloak-user-password"
      rewrite:
        - transform:
            template: "keycloakUserPassword"

---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: postgres-keycloak-password
  namespace: keycloak
spec:
  length: 32
  digits: 5
  symbols: 5
  symbolCharacters: "/-+"
  noUpper: false
  allowRepeat: true

---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: keycloak-user-password
  namespace: keycloak
spec:
  length: 32
  digits: 5
  symbols: 5
  symbolCharacters: "-" # No Special character as Argo CD does not support it.
  noUpper: false
  allowRepeat: true
