provider:
  packages:
    - xpkg.upbound.io/upbound/provider-family-gcp:v2.2.0
    - xpkg.upbound.io/upbound/provider-gcp-cloudplatform:v2.2.0
    - xpkg.upbound.io/upbound/provider-gcp-container:v2.2.0
    - xpkg.upbound.io/upbound/provider-gcp-dns:v2.2.0
    - xpkg.upbound.io/upbound/provider-gcp-secretmanager:v2.2.0
    - xpkg.upbound.io/upbound/provider-kubernetes:v1

function:
  packages:
    - xpkg.upbound.io/upbound/function-auto-ready:v0.5.0
    - xpkg.upbound.io/upbound/function-go-templating:v0.11.0

configuration:
  packages:
    - xpkg.upbound.io/livewyer-ops/crossplane-configuration-gcp-workload-identity:v0.0.1

webui:
  enabled: true
